http://localhost:5000/

###

http://localhost:5000/blocks

###

POST http://localhost:5000/blocks

{
    "message": "Second Block"
}

###

http://localhost:5000/blocks/67e9e6cda788168846559cd22cf1ee71ba85e7e0f47bd93998b6adc76e77895b